version: "3.7"
services:
  open-discord-translator:
    container_name: open-discord-translator
    image: ghcr.io/kalitsune/open-discord-translator:latest
    build: .
    restart: always
    environment:
      - TOKEN=[your token here] # https://discord.com/developers/applications
      - GUILD= # if set, the commands will only be available in this guild whose ID is linked here
      - SKIP_COMMAND_VALIDATION=false # if set to true, the bot will not check if the commands are up to date
      - ACCENT_COLOR=Blurple # the color of the embeds
      - DELETE_BUTTON_TIMEOUT=10 # the time in s before the delete button disappears (leave empty for infinite)
      - TRANSLATION_API_DRIVER=google_search # google_search google_cloud or deepl
      - SELECTED_LANGUAGES=en,es,fr,de,it,ja,ko,pt,ru,zh-CN,zh-TW,pl,nl,sv,ar,cs,da,fi,el,hi,hu,id,no,la,ro # the languages you want to translate to and from (comma separated)
      - GOOGLE_API_KEY= # your google API key (paid google driver)
      - DEEPL_API_KEY= # your deepl auth key (deepl driver)
      - DATABASE_PATH=database.sqlite # the path to the database file
      - DATABASE_DRIVER=sqlite # sqlite is the only driver supported for now but feel free to add more
    volumes:
      - open-discord-translator:/app/database.sqlite
volumes:
    open-discord-translator:
